version: "3"

services:
  server:
    container_name: server
    build: ./server
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
    command: bash -c "python manage.py runserver 0.0.0.0:$SERVER_PORT"
    env_file:
      - .env
    working_dir: /code/server/
    volumes:
      - ./server:/code/server

  client:
    container_name: client
    build:
      context: client
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "$CLIENT_PORT:$CLIENT_PORT"
    working_dir: /code/client/
    volumes:
      - ./client/:/code/client/
    environment:
      - REACT_APP_GRAPHQL_ENDPOINT=${REACT_APP_GRAPHQL_ENDPOINT}
